// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo56eBlGSBdmiHk0tQE46Dsue-5vZzqbw',
    appId: '1:489622145041:web:051fdad6f8db126cde49b0',
    messagingSenderId: '489622145041',
    projectId: 'caphore-mall',
    authDomain: 'caphore-mall.firebaseapp.com',
    storageBucket: 'caphore-mall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt7B_v14mUApR68sbQlErl2ah7evh0DE8',
    appId: '1:489622145041:android:6463aa6212910012de49b0',
    messagingSenderId: '489622145041',
    projectId: 'caphore-mall',
    storageBucket: 'caphore-mall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDBE4nq0ZfJUpxNwiISAXVwIvLN_AnPNg',
    appId: '1:489622145041:ios:8ad3d316fc9da0a9de49b0',
    messagingSenderId: '489622145041',
    projectId: 'caphore-mall',
    storageBucket: 'caphore-mall.appspot.com',
    iosBundleId: 'sy.caphore',
  );
}
